// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aws: [{ type: 'autogenerated', dirName: 'aws-sam' }],
  dynamodb: [{ type: 'autogenerated', dirName: 'dynamo-db' }]
};

module.exports = sidebars;
